// Mock data for the dashboard. In a real deployment this would be replaced by
// a data layer (database, API) — for the scaffold everything is static and
// served in-process so the dashboard renders without any backend.

import type { CrewMember, Equipment, Job, Kpi } from "./types";

export const kpis: Kpi[] = [
  {
    label: "Active jobs",
    value: "8",
    change: 14,
    hint: "vs. last month",
  },
  {
    label: "Equipment utilization",
    value: "76%",
    change: 5,
    hint: "fleet in use",
  },
  {
    label: "Crew on site",
    value: "23",
    change: -8,
    hint: "of 31 total",
  },
  {
    label: "Backlog value",
    value: "$1.84M",
    change: 21,
    hint: "signed contracts",
  },
];

export const jobs: Job[] = [
  {
    id: "JOB-1042",
    name: "Riverside foundation dig",
    client: "Hollis Development",
    site: "418 Riverside Dr",
    status: "in_progress",
    foreman: "Maria Delgado",
    progress: 62,
    startDate: "2026-06-08",
    dueDate: "2026-07-10",
    value: 248000,
  },
  {
    id: "JOB-1043",
    name: "Highway 9 culvert trenching",
    client: "County Public Works",
    site: "Highway 9, Mile 14",
    status: "in_progress",
    foreman: "Tom Reyes",
    progress: 35,
    startDate: "2026-06-15",
    dueDate: "2026-08-01",
    value: 512000,
  },
  {
    id: "JOB-1044",
    name: "Westgate lot grading",
    client: "Westgate Retail Group",
    site: "2200 Commerce Pkwy",
    status: "scheduled",
    foreman: "Maria Delgado",
    progress: 0,
    startDate: "2026-07-06",
    dueDate: "2026-07-24",
    value: 134000,
  },
  {
    id: "JOB-1045",
    name: "Old mill demolition prep",
    client: "Brandt Industrial",
    site: "55 Mill Road",
    status: "on_hold",
    foreman: "Lena Park",
    progress: 18,
    startDate: "2026-05-20",
    dueDate: "2026-07-15",
    value: 389000,
  },
  {
    id: "JOB-1046",
    name: "Cedar Heights septic excavation",
    client: "Cedar Heights HOA",
    site: "Cedar Heights, Phase 2",
    status: "scheduled",
    foreman: "Tom Reyes",
    progress: 0,
    startDate: "2026-07-13",
    dueDate: "2026-07-30",
    value: 96000,
  },
  {
    id: "JOB-1039",
    name: "Dockside retaining wall footing",
    client: "Harbor Authority",
    site: "Pier 4",
    status: "completed",
    foreman: "Lena Park",
    progress: 100,
    startDate: "2026-04-02",
    dueDate: "2026-05-30",
    value: 421000,
  },
];

export const equipment: Equipment[] = [
  {
    id: "EX-220",
    name: "CAT 320 Excavator",
    category: "excavator",
    status: "in_use",
    location: "Riverside Dr",
    hoursLogged: 4120,
    nextServiceHours: 4250,
  },
  {
    id: "EX-221",
    name: "Komatsu PC210 Excavator",
    category: "excavator",
    status: "in_use",
    location: "Highway 9",
    hoursLogged: 2980,
    nextServiceHours: 3100,
  },
  {
    id: "DZ-110",
    name: "CAT D6 Dozer",
    category: "bulldozer",
    status: "maintenance",
    location: "Main yard",
    hoursLogged: 6740,
    nextServiceHours: 6750,
  },
  {
    id: "BH-080",
    name: "JCB 3CX Backhoe",
    category: "backhoe",
    status: "available",
    location: "Main yard",
    hoursLogged: 1890,
    nextServiceHours: 2200,
  },
  {
    id: "SS-045",
    name: "Bobcat S650 Skid Steer",
    category: "skid_steer",
    status: "in_use",
    location: "Mill Road",
    hoursLogged: 3310,
    nextServiceHours: 3500,
  },
  {
    id: "DT-301",
    name: "Mack Granite Dump Truck",
    category: "dump_truck",
    status: "available",
    location: "Main yard",
    hoursLogged: 88200,
    nextServiceHours: 90000,
  },
  {
    id: "CP-012",
    name: "Wacker Plate Compactor",
    category: "compactor",
    status: "available",
    location: "Main yard",
    hoursLogged: 740,
    nextServiceHours: 900,
  },
];

export const crew: CrewMember[] = [
  {
    id: "CRW-01",
    name: "Maria Delgado",
    role: "foreman",
    status: "on_site",
    assignedJob: "JOB-1042",
    certifications: ["OSHA 30", "Competent Person — Excavation"],
    phone: "555-0142",
  },
  {
    id: "CRW-02",
    name: "Tom Reyes",
    role: "foreman",
    status: "on_site",
    assignedJob: "JOB-1043",
    certifications: ["OSHA 30", "Trenching & Shoring"],
    phone: "555-0188",
  },
  {
    id: "CRW-03",
    name: "Lena Park",
    role: "foreman",
    status: "available",
    assignedJob: null,
    certifications: ["OSHA 30", "Demolition Safety"],
    phone: "555-0119",
  },
  {
    id: "CRW-04",
    name: "Darnell White",
    role: "operator",
    status: "on_site",
    assignedJob: "JOB-1042",
    certifications: ["Heavy Equipment Operator", "Excavator"],
    phone: "555-0204",
  },
  {
    id: "CRW-05",
    name: "Priya Anand",
    role: "operator",
    status: "on_site",
    assignedJob: "JOB-1043",
    certifications: ["Heavy Equipment Operator", "Dozer"],
    phone: "555-0277",
  },
  {
    id: "CRW-06",
    name: "Hector Ruiz",
    role: "laborer",
    status: "on_site",
    assignedJob: "JOB-1042",
    certifications: ["OSHA 10"],
    phone: "555-0310",
  },
  {
    id: "CRW-07",
    name: "Sam Kowalski",
    role: "surveyor",
    status: "available",
    assignedJob: null,
    certifications: ["Land Survey Tech", "GPS Grade Control"],
    phone: "555-0355",
  },
  {
    id: "CRW-08",
    name: "Gabe Fischer",
    role: "mechanic",
    status: "on_site",
    assignedJob: null,
    certifications: ["Diesel Tech", "Hydraulics"],
    phone: "555-0399",
  },
];
