// Mock data for the dashboard. In a real deployment this would be replaced by
// a data layer (database, API) — for the scaffold everything is static and
// served in-process so the dashboard renders without any backend.

import type {
  ActivityItem,
  CrewMember,
  Equipment,
  Job,
  Kpi,
  RevenuePoint,
} from "./types";

export const kpis: Kpi[] = [
  {
    label: "Active jobs",
    value: "5",
    change: 14,
    hint: "vs. last month",
  },
  {
    label: "Equipment in use",
    value: "7 of 10",
    change: 9,
    hint: "fleet utilization",
  },
  {
    label: "Crew on site",
    value: "9",
    change: 12,
    hint: "of 12 total",
  },
  {
    label: "This week revenue",
    value: "$182K",
    change: 6,
    hint: "billed to date",
  },
];

export const jobs: Job[] = [
  {
    id: "JOB-1042",
    name: "Riverside foundation dig",
    client: "Hollis Development",
    site: "418 Riverside Dr",
    status: "in_progress",
    foreman: "Maria Delgado",
    progress: 62,
    startDate: "2026-06-08",
    dueDate: "2026-07-10",
    value: 248000,
    color: "amber",
    description:
      "Excavate and shore the foundation footprint for a six-story mixed-use building, including dewatering and export of 4,200 cubic yards of spoil.",
    notes: [
      {
        id: "N-4201",
        author: "Maria Delgado",
        date: "2026-06-22",
        body: "Hit clay seam at 11 ft on the north wall — switched to the toothed bucket, production back on pace.",
      },
      {
        id: "N-4202",
        author: "Sam Kowalski",
        date: "2026-06-18",
        body: "Survey stakes reset after the utility crew moved the gas line marker. Grades verified.",
      },
    ],
  },
  {
    id: "JOB-1043",
    name: "Highway 9 culvert trenching",
    client: "County Public Works",
    site: "Highway 9, Mile 14",
    status: "in_progress",
    foreman: "Tom Reyes",
    progress: 35,
    startDate: "2026-06-15",
    dueDate: "2026-08-01",
    value: 512000,
    color: "sky",
    description:
      "Trench and bed 1,800 linear feet of reinforced concrete culvert along the Highway 9 shoulder, with traffic control and daily backfill compaction.",
    notes: [
      {
        id: "N-4301",
        author: "Tom Reyes",
        date: "2026-06-24",
        body: "Lane closure permit extended through July 15. County inspector signed off on trench box setup.",
      },
    ],
  },
  {
    id: "JOB-1044",
    name: "Westgate lot grading",
    client: "Westgate Retail Group",
    site: "2200 Commerce Pkwy",
    status: "scheduled",
    foreman: "Maria Delgado",
    progress: 0,
    startDate: "2026-07-06",
    dueDate: "2026-07-24",
    value: 134000,
    color: "emerald",
    description:
      "Rough and fine grade a 9-acre retail pad to subgrade tolerance, balancing cut and fill on site to avoid import.",
    notes: [],
  },
  {
    id: "JOB-1045",
    name: "Old mill demolition prep",
    client: "Brandt Industrial",
    site: "55 Mill Road",
    status: "on_hold",
    foreman: "Lena Park",
    progress: 18,
    startDate: "2026-05-20",
    dueDate: "2026-07-15",
    value: 389000,
    color: "rose",
    description:
      "Strip and stockpile topsoil, then excavate around the mill structure ahead of demolition. Currently paused pending an asbestos abatement clearance.",
    notes: [
      {
        id: "N-4501",
        author: "Lena Park",
        date: "2026-06-12",
        body: "Hold placed by client — abatement contractor needs two more weeks. Crew reassigned to Riverside.",
      },
    ],
  },
  {
    id: "JOB-1046",
    name: "Cedar Heights septic excavation",
    client: "Cedar Heights HOA",
    site: "Cedar Heights, Phase 2",
    status: "scheduled",
    foreman: "Tom Reyes",
    progress: 0,
    startDate: "2026-07-13",
    dueDate: "2026-07-30",
    value: 96000,
    color: "teal",
    description:
      "Excavate leach field and tank pits for 14 lots in the Phase 2 subdivision, coordinating with the septic installer's schedule.",
    notes: [],
  },
  {
    id: "JOB-1047",
    name: "Northpoint warehouse pad",
    client: "Northpoint Logistics",
    site: "780 Industrial Blvd",
    status: "in_progress",
    foreman: "Lena Park",
    progress: 48,
    startDate: "2026-06-01",
    dueDate: "2026-07-18",
    value: 604000,
    color: "violet",
    description:
      "Mass excavation and engineered fill for a 220,000 sq ft distribution warehouse pad, including undercut of unsuitable soils and import of structural fill.",
    notes: [
      {
        id: "N-4701",
        author: "Lena Park",
        date: "2026-06-26",
        body: "Geotech approved the proof roll on the east half. Moving fill operations to the west bay tomorrow.",
      },
    ],
  },
  {
    id: "JOB-1048",
    name: "Maple Street storm drain",
    client: "City of Brookfield",
    site: "Maple St & 3rd Ave",
    status: "in_progress",
    foreman: "Tom Reyes",
    progress: 71,
    startDate: "2026-05-28",
    dueDate: "2026-07-02",
    value: 218000,
    color: "orange",
    description:
      "Install 640 feet of storm drain pipe with three catch basins and a junction structure, then restore curb, gutter, and asphalt.",
    notes: [
      {
        id: "N-4801",
        author: "Tom Reyes",
        date: "2026-06-27",
        body: "Last catch basin set. Paving sub scheduled for the restoration on July 1.",
      },
    ],
  },
  {
    id: "JOB-1039",
    name: "Dockside retaining wall footing",
    client: "Harbor Authority",
    site: "Pier 4",
    status: "completed",
    foreman: "Lena Park",
    progress: 100,
    startDate: "2026-04-02",
    dueDate: "2026-05-30",
    value: 421000,
    color: "indigo",
    description:
      "Excavate and dewater the footing trench for a 300-foot precast retaining wall along the waterfront, completed two days ahead of schedule.",
    notes: [
      {
        id: "N-3901",
        author: "Lena Park",
        date: "2026-05-28",
        body: "Punch list cleared. Final survey as-builts delivered to the Harbor Authority.",
      },
    ],
  },
  {
    id: "JOB-1040",
    name: "Linden Park pond dredging",
    client: "Linden Parks Dept",
    site: "Linden Park",
    status: "completed",
    foreman: "Maria Delgado",
    progress: 100,
    startDate: "2026-03-10",
    dueDate: "2026-04-28",
    value: 167000,
    color: "cyan",
    description:
      "Dredge 6,000 cubic yards of accumulated silt from the park's retention pond and regrade the banks for erosion control.",
    notes: [],
  },
  {
    id: "JOB-1049",
    name: "Tech campus mass grading",
    client: "Meridian Real Estate",
    site: "Innovation Way",
    status: "scheduled",
    foreman: "Maria Delgado",
    progress: 0,
    startDate: "2026-07-20",
    dueDate: "2026-09-12",
    value: 1240000,
    color: "fuchsia",
    description:
      "Phase 1 mass grading of a 40-acre corporate campus: 90,000 cubic yards of cut-to-fill, detention basin excavation, and haul road construction.",
    notes: [
      {
        id: "N-4901",
        author: "Sam Kowalski",
        date: "2026-06-25",
        body: "Preliminary GPS model loaded into the dozers. Awaiting the final geotech report before mobilizing.",
      },
    ],
  },
];

export const equipment: Equipment[] = [
  {
    id: "EX-220",
    name: "CAT 320 Excavator",
    category: "excavator",
    status: "in_use",
    location: "Riverside Dr",
    assignedJob: "JOB-1042",
    hoursLogged: 4120,
    nextServiceHours: 4250,
  },
  {
    id: "EX-221",
    name: "Komatsu PC210 Excavator",
    category: "excavator",
    status: "in_use",
    location: "Highway 9",
    assignedJob: "JOB-1043",
    hoursLogged: 2980,
    nextServiceHours: 3100,
  },
  {
    id: "EX-222",
    name: "CAT 336 Excavator",
    category: "excavator",
    status: "in_use",
    location: "Industrial Blvd",
    assignedJob: "JOB-1047",
    hoursLogged: 1560,
    nextServiceHours: 1800,
  },
  {
    id: "DZ-110",
    name: "CAT D6 Dozer",
    category: "bulldozer",
    status: "maintenance",
    location: "Main yard",
    assignedJob: null,
    hoursLogged: 6740,
    nextServiceHours: 6750,
  },
  {
    id: "DZ-111",
    name: "Komatsu D65 Dozer",
    category: "bulldozer",
    status: "in_use",
    location: "Industrial Blvd",
    assignedJob: "JOB-1047",
    hoursLogged: 3920,
    nextServiceHours: 4200,
  },
  {
    id: "BH-080",
    name: "JCB 3CX Backhoe",
    category: "backhoe",
    status: "in_use",
    location: "Maple St",
    assignedJob: "JOB-1048",
    hoursLogged: 1890,
    nextServiceHours: 2200,
  },
  {
    id: "SS-045",
    name: "Bobcat S650 Skid Steer",
    category: "skid_steer",
    status: "available",
    location: "Main yard",
    assignedJob: null,
    hoursLogged: 3310,
    nextServiceHours: 3500,
  },
  {
    id: "DT-301",
    name: "Mack Granite Dump Truck",
    category: "dump_truck",
    status: "in_use",
    location: "Industrial Blvd",
    assignedJob: "JOB-1047",
    hoursLogged: 88200,
    nextServiceHours: 90000,
  },
  {
    id: "DT-302",
    name: "Peterbilt 567 Dump Truck",
    category: "dump_truck",
    status: "available",
    location: "Main yard",
    assignedJob: null,
    hoursLogged: 61400,
    nextServiceHours: 64000,
  },
  {
    id: "GR-070",
    name: "CAT 140 Motor Grader",
    category: "grader",
    status: "available",
    location: "Main yard",
    assignedJob: null,
    hoursLogged: 2210,
    nextServiceHours: 2600,
  },
  {
    id: "LD-055",
    name: "CAT 950 Wheel Loader",
    category: "loader",
    status: "in_use",
    location: "Maple St",
    assignedJob: "JOB-1048",
    hoursLogged: 5040,
    nextServiceHours: 5300,
  },
  {
    id: "CP-012",
    name: "Wacker Plate Compactor",
    category: "compactor",
    status: "available",
    location: "Main yard",
    assignedJob: null,
    hoursLogged: 740,
    nextServiceHours: 900,
  },
];

export const crew: CrewMember[] = [
  {
    id: "CRW-01",
    name: "Maria Delgado",
    role: "foreman",
    status: "on_site",
    assignedJob: "JOB-1042",
    certifications: ["OSHA 30", "Competent Person — Excavation"],
    phone: "555-0142",
  },
  {
    id: "CRW-02",
    name: "Tom Reyes",
    role: "foreman",
    status: "on_site",
    assignedJob: "JOB-1043",
    certifications: ["OSHA 30", "Trenching & Shoring"],
    phone: "555-0188",
  },
  {
    id: "CRW-03",
    name: "Lena Park",
    role: "foreman",
    status: "on_site",
    assignedJob: "JOB-1047",
    certifications: ["OSHA 30", "Demolition Safety"],
    phone: "555-0119",
  },
  {
    id: "CRW-04",
    name: "Darnell White",
    role: "operator",
    status: "on_site",
    assignedJob: "JOB-1042",
    certifications: ["Heavy Equipment Operator", "Excavator"],
    phone: "555-0204",
  },
  {
    id: "CRW-05",
    name: "Priya Anand",
    role: "operator",
    status: "on_site",
    assignedJob: "JOB-1043",
    certifications: ["Heavy Equipment Operator", "Dozer"],
    phone: "555-0277",
  },
  {
    id: "CRW-06",
    name: "Hector Ruiz",
    role: "laborer",
    status: "on_site",
    assignedJob: "JOB-1042",
    certifications: ["OSHA 10"],
    phone: "555-0310",
  },
  {
    id: "CRW-07",
    name: "Sam Kowalski",
    role: "surveyor",
    status: "available",
    assignedJob: null,
    certifications: ["Land Survey Tech", "GPS Grade Control"],
    phone: "555-0355",
  },
  {
    id: "CRW-08",
    name: "Gabe Fischer",
    role: "mechanic",
    status: "on_site",
    assignedJob: null,
    certifications: ["Diesel Tech", "Hydraulics"],
    phone: "555-0399",
  },
  {
    id: "CRW-09",
    name: "Wes Carter",
    role: "operator",
    status: "on_site",
    assignedJob: "JOB-1047",
    certifications: ["Heavy Equipment Operator", "Loader", "Grader"],
    phone: "555-0421",
  },
  {
    id: "CRW-10",
    name: "Aisha Bello",
    role: "operator",
    status: "on_site",
    assignedJob: "JOB-1048",
    certifications: ["Heavy Equipment Operator", "Backhoe"],
    phone: "555-0468",
  },
  {
    id: "CRW-11",
    name: "Diego Marin",
    role: "laborer",
    status: "on_site",
    assignedJob: "JOB-1048",
    certifications: ["OSHA 10", "Confined Space Entry"],
    phone: "555-0502",
  },
  {
    id: "CRW-12",
    name: "Janet Cole",
    role: "laborer",
    status: "available",
    assignedJob: null,
    certifications: ["OSHA 10", "Flagger"],
    phone: "555-0537",
  },
];

/** Weekly billed revenue for the trailing eight weeks. */
export const weeklyRevenue: RevenuePoint[] = [
  { week: "May 4", revenue: 124000 },
  { week: "May 11", revenue: 138000 },
  { week: "May 18", revenue: 116000 },
  { week: "May 25", revenue: 152000 },
  { week: "Jun 1", revenue: 168000 },
  { week: "Jun 8", revenue: 159000 },
  { week: "Jun 15", revenue: 174000 },
  { week: "Jun 22", revenue: 182000 },
];

export const activity: ActivityItem[] = [
  {
    id: "ACT-01",
    kind: "report_submitted",
    title: "Daily report submitted — Maple Street storm drain",
    detail: "Tom Reyes logged 8.5 crew-hours and the final catch basin set.",
    timestamp: "2026-06-29T15:10:00",
    jobId: "JOB-1048",
  },
  {
    id: "ACT-02",
    kind: "equipment_moved",
    title: "CAT 950 Wheel Loader moved to Maple St",
    detail: "Relocated from the yard to support storm drain restoration.",
    timestamp: "2026-06-29T13:25:00",
    jobId: "JOB-1048",
  },
  {
    id: "ACT-03",
    kind: "crew_assigned",
    title: "Wes Carter assigned to Northpoint warehouse pad",
    detail: "Operator added to run the D65 dozer on the west bay fill.",
    timestamp: "2026-06-29T08:05:00",
    jobId: "JOB-1047",
  },
  {
    id: "ACT-04",
    kind: "report_submitted",
    title: "Daily report submitted — Riverside foundation dig",
    detail: "Maria Delgado noted clay seam cleared, production on pace.",
    timestamp: "2026-06-28T16:40:00",
    jobId: "JOB-1042",
  },
  {
    id: "ACT-05",
    kind: "equipment_moved",
    title: "CAT 336 Excavator moved to Industrial Blvd",
    detail: "Dispatched to Northpoint for the structural fill undercut.",
    timestamp: "2026-06-28T07:50:00",
    jobId: "JOB-1047",
  },
  {
    id: "ACT-06",
    kind: "job_started",
    title: "Northpoint warehouse pad — fill operations started",
    detail: "Lena Park mobilized the fill crew after the east-half proof roll.",
    timestamp: "2026-06-26T07:30:00",
    jobId: "JOB-1047",
  },
  {
    id: "ACT-07",
    kind: "crew_assigned",
    title: "Aisha Bello assigned to Maple Street storm drain",
    detail: "Backhoe operator added for the junction structure install.",
    timestamp: "2026-06-25T09:15:00",
    jobId: "JOB-1048",
  },
  {
    id: "ACT-08",
    kind: "job_completed",
    title: "Dockside retaining wall footing completed",
    detail: "Lena Park closed the punch list two days ahead of schedule.",
    timestamp: "2026-05-28T14:20:00",
    jobId: "JOB-1039",
  },
];
